
server:
  port: 8762

#需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service-hi
  cloud:
    client:
      ipAddress: 192.168.28.84

#服务注册中心的地址
eureka:
  client:
   serviceUrl:
    defaultZone: http://192.168.28.84:8761/eureka/
    #如果要在服务注册中心显示真正的ip地址就要配置下面这个
  #instance:
    #prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}





